Remove function names
Named function 'mask' causes strict mode violation in Safari:

SyntaxError: Cannot declare a parameter named 'mask' as it shadows
the name of a strict mode function.

Fixes #46